version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: petshop_postgres
    environment:
      POSTGRES_USER: petshop_user
      POSTGRES_PASSWORD: petshop_password
      POSTGRES_DB: petshop_db
    ports:
      - "5532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U petshop_user -d petshop_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: